# Generated by Django 4.0.1 on 2022-01-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollenMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollen_type', models.CharField(max_length=100)),
                ('pollen_count', models.CharField(max_length=200)),
                ('measurement_location', models.CharField(max_length=200)),
                ('measurement_time', models.DateTimeField(verbose_name='measurement_time')),
            ],
        ),
    ]
